// @vitest-environment jsdom

import { beforeEach, describe, expect, it } from 'vitest';
import Canvas from '../src/canvas';
import KonvaPainter from '../src/konva-painter';
import { flipflop } from '../src/sequence';

function createContainer(id: string): HTMLDivElement {
  const div = document.createElement('div');
  div.id = id;
  document.body.appendChild(div);
  return div;
}

describe('konva-painter (jsdom)', () => {
  beforeEach(() => {
    document.body.innerHTML = '';
  });

  it('initializes a Konva stage and layer on the container', () => {
    createContainer('konva-init');
    const canvas = new Canvas('konva-init', {
      width: 400,
      height: 300,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    expect(canvas._konvaLayer).toBeDefined();
    expect(canvas._konvaLayer!.getStage().width()).toBe(400);
    expect(canvas._konvaLayer!.getStage().height()).toBe(300);
  });

  it('sketches and draws an autogenerated puzzle without throwing', () => {
    createContainer('konva-draw');
    const canvas = new Canvas('konva-draw', {
      width: 600,
      height: 600,
      pieceSize: 50,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 2,
      horizontalPiecesCount: 2,
      insertsGenerator: flipflop,
    });
    expect(() => canvas.draw()).not.toThrow();
    expect(canvas.figuresCount).toBe(4);
    for (const piece of canvas.puzzle.pieces) {
      const figure = canvas.getFigure(piece);
      expect(figure.group).toBeDefined();
      expect(figure.shape).toBeDefined();
    }
  });

  it('resizes the underlying stage', () => {
    createContainer('konva-resize');
    const canvas = new Canvas('konva-resize', {
      width: 200,
      height: 200,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.resize(800, 500);
    const stage = canvas._konvaLayer!.getStage();
    expect(stage.width()).toBe(800);
    expect(stage.height()).toBe(500);
  });

  it('scales the underlying stage', () => {
    createContainer('konva-scale');
    const canvas = new Canvas('konva-scale', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.scale({ x: 2, y: 3 });
    const stage = canvas._konvaLayer!.getStage();
    expect(stage.scaleX()).toBe(2);
    expect(stage.scaleY()).toBe(3);
  });

  it('clear() reinitializes the layer so the canvas can be redrawn', () => {
    createContainer('konva-clear');
    const canvas = new Canvas('konva-clear', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 2,
      horizontalPiecesCount: 2,
      insertsGenerator: flipflop,
    });
    canvas.draw();
    canvas.clear();
    expect(canvas._drawn).toBe(false);
    expect(canvas.figures).toEqual({});
    expect(() => canvas.draw()).not.toThrow();
  });

  it('renders piece labels through the painter', () => {
    createContainer('konva-label');
    const canvas = new Canvas('konva-label', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      metadata: [{ label: { text: 'hello', fontSize: 12 } }],
    });
    canvas.draw();
    const [piece] = canvas.puzzle.pieces;
    const figure = canvas.getFigure(piece);
    expect(figure.label).toBeDefined();
    expect(figure.label!.text()).toBe('hello');
  });

  it('fills pieces with an image when imageMetadata is provided', () => {
    createContainer('konva-fill');
    const img = document.createElement('canvas');
    img.width = 100;
    img.height = 100;
    const canvas = new Canvas('konva-fill', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      image: img,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    // Stub the actual rasterization step: jsdom + node-canvas don't fully
    // support the DOMMatrix path needed to render fillPatternImage. We only
    // need to assert that the painter wires the pattern image into the shape.
    canvas._konvaLayer!.draw = () => canvas._konvaLayer!;
    canvas.draw();
    const [piece] = canvas.puzzle.pieces;
    const figure = canvas.getFigure(piece);
    expect(figure.shape!.fillPatternImage()).toBe(img);
  });

  it('refill() updates the image fill on existing figures', () => {
    createContainer('konva-refill');
    const img1 = document.createElement('canvas');
    img1.width = 50;
    img1.height = 50;
    const canvas = new Canvas('konva-refill', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      image: img1,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    canvas._konvaLayer!.draw = () => canvas._konvaLayer!;
    canvas.draw();

    const img2 = document.createElement('canvas');
    img2.width = 80;
    img2.height = 80;
    canvas.imageMetadata = { content: img2, offset: { x: 1, y: 1 }, scale: 1 };
    canvas.refill();

    const [piece] = canvas.puzzle.pieces;
    expect(canvas.getFigure(piece).shape!.fillPatternImage()).toBe(img2);
  });

  it('logically translates pieces to match group positions', () => {
    createContainer('konva-translate');
    const canvas = new Canvas('konva-translate', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    canvas.draw();
    const [piece] = canvas.puzzle.pieces;
    const group = canvas.getFigure(piece).group!;
    group.x(123);
    group.y(45);
    new KonvaPainter().logicalTranslate(canvas, piece, group);
    expect(piece.metadata.currentPosition).toEqual({ x: 123, y: 45 });
  });

  it('physically translates groups to match the piece anchor', () => {
    createContainer('konva-physical');
    const canvas = new Canvas('konva-physical', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    canvas.draw();
    const [piece] = canvas.puzzle.pieces;
    const group = canvas.getFigure(piece).group!;
    piece.relocateTo(200, 150);
    new KonvaPainter().physicalTranslate(canvas, group, piece);
    expect(group.x()).toBe(200);
    expect(group.y()).toBe(150);
  });

  it('registers keyboard gestures and triggers them on key events', () => {
    const container = createContainer('konva-keys');
    const canvas = new Canvas('konva-keys', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    canvas.draw();

    let pressed = 0;
    canvas.registerKeyboardGestures({
      a: () => {
        pressed++;
      },
    });

    // Konva uses its own container element inside our div
    const stageContainer = canvas._konvaLayer!.getStage().container();
    stageContainer.dispatchEvent(new KeyboardEvent('keydown', { key: 'a' }));
    stageContainer.dispatchEvent(new KeyboardEvent('keyup', { key: 'a' }));
    expect(pressed).toBe(1);
    expect(stageContainer.tabIndex).toBe(-1);
    expect(container.contains(stageContainer)).toBe(true);
  });

  it('fires drag-end callback through onDragEnd wiring', () => {
    createContainer('konva-dragend');
    const canvas = new Canvas('konva-dragend', {
      width: 400,
      height: 400,
      pieceSize: 40,
      proximity: 10,
      painter: new KonvaPainter(),
    });
    canvas.autogenerate({
      verticalPiecesCount: 1,
      horizontalPiecesCount: 1,
      insertsGenerator: flipflop,
    });
    canvas.draw();
    const [piece] = canvas.puzzle.pieces;
    const group = canvas.getFigure(piece).group!;
    let ended = 0;
    new KonvaPainter().onDragEnd(canvas, piece, group, () => {
      ended++;
    });
    group.fire('dragend');
    expect(ended).toBe(1);
  });
});
